language: node_js
sudo: false
dist: trusty
cache:
  directories:
    - node_modules
addons:
  chrome: stable
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start  
branches:
  only:
  - master
node_js:
  - '6'
  - '7'
  - '8'
script:
  - npm test